theme: jekyll-theme-minimal

title: [Epidemia, nube radiactiva y distanciamiento social]
description: [Este articulo es una traducción de un articulo de David Louapre en su blog "Science Etonnante". El articulo fue traducido y publicado con autorización del autor original, pero el contenido traducido no esta bajo su responsabilidad. El texto original esta disponible directamente en el blog del autor.]
